repos:
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        require_serial: true
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [-l 100]
        require_serial: true
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true