repos:
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [-l 100]
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false
    -   id: docs
        name: make documentation
        entry: make
        language: system
        types: [python]
        args: [docs]
        pass_filenames: false
